In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


Introduction to Tensors - Creating tensors

In [ ]:
# scalars
scalar = torch.tensor(7)
scalar.ndim

0

In [ ]:
scalar.item

<function Tensor.item>

In [ ]:
# vectors
vector = torch.tensor([7,7,7])
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
# matrix
MATRIX = torch.tensor([[1,2],
                     [3,4]])
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([3, 4])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Random Tensors

Random tensors are important because the way many neural networks work is that they start with tensors full of random numbers and then adjust random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers -> etc

In [ ]:
# creating a random tensor
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.2740, 0.3749, 0.9665, 0.4669],
        [0.3045, 0.4909, 0.1412, 0.5091],
        [0.2058, 0.0091, 0.1083, 0.4277]])

In [ ]:
# create random tensor with similar shape to an image tensor
rand_im_size_tensor = torch.rand(size=(3,224,224)) # height, width, color channel
rand_im_size_tensor.shape, rand_im_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange() instead of torch.range()
eg_range = torch.arange(start=0, end=1000, step=69)
eg_range

tensor([  0,  69, 138, 207, 276, 345, 414, 483, 552, 621, 690, 759, 828, 897,
        966])

In [ ]:
# Creating tensors like
eg_like = torch.zeros_like(input=eg_range) # takes eg_range as input and creates a similar tensor with whatever like (same shape, different values)
eg_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,4.0,5.0],
                               dtype=None, # what datatype is the tensor (like 32-bit float, 16-bit float, etc.) (precision in computing)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 4., 5.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# Changing datatypes
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [ ]:
# Multiplying different datatypes
multiplying_dtypes = float_16_tensor * float_32_tensor
multiplying_dtypes.dtype

torch.float32

### Getting information from tensors - Tensor Attributes

1. Tensors not right datatype - to get datatype from a tensor, can use 'tensor.dype'
2. Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,3)
some_tensor

tensor([[0.4978, 0.1221, 0.9842],
        [0.9623, 0.5754, 0.6449],
        [0.2963, 0.4008, 0.0117]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.4978, 0.1221, 0.9842],
        [0.9623, 0.5754, 0.6449],
        [0.2963, 0.4008, 0.0117]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 3])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10) # generally use python operators, but these are essentially the same
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication need to satisfy:
1. The **inner dimensions** must match:
* need (a, b) * (b, c), where inner dimensions are same
2. The resulting matrix has the shape of the **outer dimensions**
* (a, b) * (b, c) results in shape (a, c)

In [ ]:
# Element wise multiplicaiton
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}") # if you add these up, you get the dot product

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor) # could also use torch.mm instead of torch.matmul

tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor(([[1,2],
                          [3,4],
                          [5,6]]))

tensor_B = torch.tensor(([[7,10],
                          [8,11],
                          [9,12]]))

torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul
# creates a shape error obviously, middle dim don't match

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**
A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape # Perform a transpose, switching rows to columns

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_A, tensor_B.T) # This works now because second matrix has same inner dimension now!

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Find max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# Find the mean - requires a tensor of float32 dtype to work
torch.mean(x.type(torch.float32)) # have to convert dtype for mean to work

tensor(46.)

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finging the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimun value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

### Reshaping, stacking squeezing and undsqueexing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of eachother (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) a certain way

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 11.) # has size 10
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(5, 2) # 5*2 = 10, so it works (10=10)
x_reshaped

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
# Change the view
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z,x # still the same

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# Stack tensors on top of eachother
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
# torch.squeeze() - removes all single dimesnions from a target tensor
x_squeezed = x.squeeze()
x_squeezed

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
x_squeezed.shape

torch.Size([10])

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[ 5.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [ ]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's inde on the inner most bracket (last dim)
x[0][0][0]

tensor(1)

In [ ]:
# Can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

### PyTorch Tensors & NumPy
NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.
* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will this to do `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducability (trying to take random iout of random)
In short, how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again...

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavor" the randomness

In [ ]:
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # have to set each time, can't just do it once at the top
random_tensor_B = torch.rand(3,4)

print(random_tensor_A == random_tensor_B)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch, since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:
(eg. run on GPU if possible, otherwise default to CPU)

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

### Exercises and Extracuricular
https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [ ]:
# Create a random tensor with shape (7, 7).
rand_tensor_A = torch.rand(7,7)

In [ ]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
rand_tensor_A = torch.rand(7,7)
rand_tensor_B = torch.rand(1,7)
torch.mm(rand_tensor_A, rand_tensor_B.T)

tensor([[2.0491],
        [1.4719],
        [1.9037],
        [1.2220],
        [2.6336],
        [1.4222],
        [2.3889]])

In [ ]:
# Set the random seed to 0 and do exercises 2 & 3 over again.
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
rand_tensor_A = torch.rand(7,7)

torch.manual_seed(RANDOM_SEED)
rand_tensor_B = torch.rand(1,7)

torch.mm(rand_tensor_A, rand_tensor_B.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [ ]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
 # (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
torch.cuda.manual_seed(1234)

In [ ]:
# Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [ ]:
# Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
tensor_C = torch.mm(tensor_A, tensor_B.T)

In [ ]:
# Find the maximum and minimum values of the output of 7.
print(tensor_C.min(), tensor_C.max())

tensor(0.3647, device='cuda:0') tensor(0.5617, device='cuda:0')


In [ ]:
# Find the maximum and minimum index values of the output of 7.
print(tensor_C.argmin(), tensor_C.argmax())

tensor(0, device='cuda:0') tensor(3, device='cuda:0')


In [ ]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be
# left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape
# as well as the second tensor and it's shape.

torch.manual_seed(7)

rand_tensor_D = torch.rand(size=(1,1,1,10))
rand_tensor_D_adjusted = rand_tensor_D.squeeze()

print(rand_tensor_D, rand_tensor_D.shape)
print(rand_tensor_D_adjusted, rand_tensor_D_adjusted.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
